# Rename this file to fconfig.yaml and fill in the values

elasticsearch:
  host: "hostname"
  port: 9200
  scheme: "http" # or "https"
  user: "elastic" # elastic is the default user on Elasticsearch
  password: "secret_password" # the password for the user
index: "faker-logs"
log_generation:
  interval_min: 0.5
  interval_max: 2.0
  num_logs: 1000  # Set to -1 for infinite log generation